server:
  port: 9091

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test_database
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  backoff:
    interval: 10000
    max_failure: 3
  topic:
    single-message: kafka-single-message